table Regions
	lineageTag: b01700e3-07da-4f4e-af58-72885bbacbfc

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: c6f9886b-c41f-4183-b380-c2afa4068c96
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fb3a72ea-07ad-4d2e-acc2-1b13b6121983
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition Regions-a0dca82a-0f97-4af8-9b2f-44d1a96c6e61 = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQrNyyxJTVEILkksSS1WitWJVjICirqWFuUXpIK5xkCuY3FmolJsLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [RegionID = _t, Region = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"RegionID", Int64.Type}, {"Region", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

